### ISSUE TITLE
glossary에 추가할 내용

### ISSUE THREAD

**Issue by uriyang** [beewee22/svelte.kr#13]
어느 정도의 용어까지 넣을지~
glossary에 넣을 단어와 아닌 단어의 기준을 어떤 방식으로 결정할 지 정해 보아요~~~

**Comment by beewee22** [comment]
Should be added to #12 
일단, 스벨트에서만 사용되는 고유명사가 추가되어야 할 것 같고, 그 외에는 다른 곳에서도 여러 단어로 혼용하는 단어를 주관적으로 추가하면 될 것 같아요. 

Glossary 자체는 다다익선이지 않나.. 싶은 생각인데, 가능하면 일반적인 단어는 다른 유명 번역 게시물(MDN이나 React, Vue 공식 홈페이지 등)을 따르는게 좋을 것 같구요.

**Comment by uriyang** [comment]
네넵~ 그러면 지금까지 번역 진행된 부분에서 svelte 고유영역이라고 생각한 항목만 넣었는데, 더 넣거나 빼야할 항목들이 있을까요?

**Comment by uriyang** [comment]
@beewee22 
해당 내용 수정해서, PR 날렸습니다~
https://github.com/beewee22/svelte.kr/pull/12

**Comment by beewee22** [comment]
> @beewee22
> 해당 내용 수정해서, PR 날렸습니다~
> #12

머지 완료되었고, 이제 단어장은 [여기](https://github.com/beewee22/svelte.kr/blob/master/docs/reference-glossary.md)에 업데이트 해 주시면 될 것 같습니다!
