### ISSUE TITLE
문의 드립니다!

### ISSUE THREAD

**Issue by soulcactus** [beewee22/svelte.kr#15]
안녕하세요, 스벨트 저장소에 한국어 번역 허가 받고 저장소 검색해 보는데 이미 진행중인 저장소가 있어서 컨트리뷰터로 참여 가능한지 문의드립니다! 가능하다면 진행방식에 대해서도 알고 싶습니다. :) 러시아의 경우 스벨트 저장소를 다운 받은 다음 파일들을 모두 번역하는 방식으로 진행했다고 합니다. 번역이 완료되면 스벨트 공식 사이트에 연결 가능하다는 답변도 얻었습니다. 러시아의 경우는 다음과 같습니다. http://ru.svelte.dev/

**Comment by beewee22** [comment]
오, 안녕하세요! 저도 작년에 리치 해리스에게서 직접 허가를 받긴 했는데, 그 때엔 스벨트가 i18n 지원을 예정 중이라 그게 완료가 되면 도메인 통합을 지원해 줄 수 있을거란 답변을 들었었거든요.
(해당 답변 링크: https://twitter.com/Rich_Harris/status/1164910702861139970)

현재 사실상 번역은 휴면상태(..)인데, REPL에 들어있던 postgreSQL의 크레덴셜이 없다던가하는 이슈를 어떻게 극복할지에 대해서 토론하다가 스벨트 업데이트 상황을 보기로 한 상태였어요.

컨트리뷰트 해주신다면 정말 감사히 함께하고 싶습니다!
러시아의 사례를 보고 저희도 따라서 하면 될 것 같습니다!
공식 사이트 도메인에 올라갈 수 있다는 답변을 들으신 것도 고무적이네요!

괜찮으시다면 번역 멤버들이 가입되어있는 슬랙에 초대드려서 커뮤니케이션 해도 괜찮을까요?

**Comment by soulcactus** [comment]
답변 고맙습니다! 제 이메일은 sunhyejin@mensakorea.org입니다! 초대해 주시면 감사하겠습니다. 😊

**Comment by uriyang** [comment]
환영합니다~ ^_^

**Comment by soulcactus** [comment]
반갑습니다 😃

**Comment by beewee22** [comment]
> 답변 고맙습니다! 제 이메일은 [sunhyejin@mensakorea.org](mailto:sunhyejin@mensakorea.org)입니다! 초대해 주시면 감사하겠습니다. 😊

슬랙 인바이트 드렸습니다! 환영합니다!

**Comment by uriyang** [comment]
러시아 리포 참고해서 새 브랜치 구성하는 걸로 변경되었습니다.
