### ISSUE TITLE
translate glossary

### ISSUE THREAD

**Issue by SeongJuMoon** [beewee22/svelte.kr#2]
See https://github.com/reactjs/ko.reactjs.org/issues/2

**Comment by beewee22** [comment]
저희도 .md 파일로 관리할까요????

어떤게 더 편할까요? google docs 스프레드시트로 해도 되고, 이 repo에 아예 md 파일로 관리해도 될 것 같긴 한데..

**Comment by SeongJuMoon** [comment]
> 저희도 .md 파일로 관리할까요????
> 
> 어떤게 더 편할까요? google docs 스프레드시트로 해도 되고, 이 repo에 아예 md 파일로 관리해도 될 것 같긴 한데..

해당 레포에 md 파일로 관리하는 것이 나을듯 합니다. 아니면 그냥 둘다 운영해도 괜찮을꺼 같구요

**Comment by beewee22** [comment]
md파일 머지 완료되었어요! 여기에 일단 지금 README.md 에서 번역한 부분을 업데이트 해둬야겠네요. 오늘 가능하면 작업해볼게요

**Comment by uriyang** [comment]
넵~ 이 파일 사용법을 아직 정확히 모르겠어서, 샘플 보고 참고해보도록 할께요 ^^

**Comment by beewee22** [comment]
md파일 생성이 완료되었으므로, 이 이슈는 닫습니다.
