### ISSUE TITLE
메인 컨텐츠 구성은 어떻게 되어야 할까요?

### ISSUE THREAD

**Issue by beewee22** [beewee22/svelte.kr#3]
제 생각엔, 상단에 있는 소개글까지만 번역하고, 그 뒤엔 저희가 컨텐츠를 만들던가 해야할 것 같아요 @_@

**Comment by uriyang** [comment]
저도 만드는 게 더 좋을 것 같아요~

**Comment by beewee22** [comment]
그럼 만드는걸로 하고, 어떤 내용이 들어가야 좋을지를 고민해봐야 할 것 같아요

**Comment by uriyang** [comment]
잘 되있는 도큐먼트부터 벤치마킹 해보면 어떨까요?
일단은 vue나 react정도?

그리고 그렇다면 top down, bottom up 방식으로 갈지 고민해보는것도 좋을 것 같아요 ^^

**Comment by beewee22** [comment]
https://kr.vuejs.org/
https://ko.reactjs.org/

둘 다 기본적으론 공식 홈페이지에서 따온거라 같은 구성이긴 한데요, 현재 스벨트랑 리액트는 비슷하네요.

저희도 그 상단의 간단한 소개만 하고 예제코드로 보여주면 될까요..?

**Comment by uriyang** [comment]
저는 괜찮을 것 같아요
그렇게 진행하다가, 더 나은 부분이 있으면 그때 좀 더 구체화 해도 될 것 같아요

**Comment by beewee22** [comment]
방금 슬랙에서 나온, Vue, React와의 비교를 간단하게 만들어보면 어떨까요??

**Comment by SeongJuMoon** [comment]
>  방금 슬랙에서 나온, Vue, React와의 비교를 간단하게 만들어보면 어떨까요??

그렇게 하면 사람들이 진입하기에 좋을꺼 같아요

**Comment by beewee22** [comment]
## 현재까지 정리

### 메인에 들어갈 컨텐츠
- svelte.dev 메인 상단의 svelte 소개
- Vue/React/Svelte 비교

**Comment by SeongJuMoon** [comment]
> Vue/React/Svelte 비교

간단하게 to-do list 코드로 비교하는게 어떨까요?

**Comment by ENvironmentSet** [comment]
저희가 만들려는 건 i18n 사이트이니 원본에 충실하게 작업하는 게  좋지 않을까요?

**Comment by SeongJuMoon** [comment]
> 저희가 만들려는 건 i18n 사이트이니 원본에 충실하게 작업하는 게 좋지 않을까요?

좋습니다 👍

**Comment by beewee22** [comment]
> 저희가 만들려는 건 i18n 사이트이니 원본에 충실하게 작업하는 게 좋지 않을까요?

안타깝게도 스벨트 메인 페이지 컨텐츠의 반 이상이 REPL을 포함하고 있고, 그 REPL은 자체적인 postgreSQL의 크레덴셜을 기반으로 돌고 있어 원본에 충실할 수 있는 방법이 없어 궁여지책을 고민할 수 밖에 없었습니다. 그걸 위한 이슈였구요.

**Comment by uriyang** [comment]
러시아 리포 참고해서 새 브랜치 구성하는 걸로 변경되었습니다.
