### ISSUE TITLE
https://svelte.dev/docs.json 파싱

### ISSUE THREAD

**Issue by beewee22** [beewee22/svelte.kr#7]
조사 결과, https://svelte.dev/docs 의 컨텐츠는 json 파일로 되어있는걸 SSR 번들 단계에서 파싱하는 것으로 확인되었습니다.

저희가 원본 그대로의 사이트를 가져오기에는 필요한 Credential(예> PostgreSQL)을 받아낼 수 없어 정상작동이 불가능한 상황이라, 이 부분도 일단 저희가 다운로드 받아서 파싱을 해야할 것 같아요.

그래서 아이디어를 모아 보아야 할 부분은,

1. docs.json을 어떤 형식으로 파싱 할 것인가?
2. docs.json에서 업데이트 되는 부분은 어떻게 할 것인가?

입니다. 일단 자유롭게 의견 주세요!

**Comment by SeongJuMoon** [comment]
> docs.json을 어떤 형식으로 파싱 할 것인가?

해당 json에서 slug와 html 부분을 중점적으로 깎아내기 이전에 file에 있는 md 파일부터 손을 봐야할 듯 하네요
> docs.json에서 업데이트 되는 부분은 어떻게 할 것인가?

막연하게 생각나는건데 세션(article) 별로 브랜치를 나눠서 `translate` branch에 작업사항을 봐가면서 하는게 어떨까요?

다른 의견이 있으시다면 남겨주세요

**Comment by uriyang** [comment]
좋습니당~

**Comment by beewee22** [comment]
Update: 현재 md파일을 먼저 번역하는 쪽으로 합의가 이루어졌습니다. 다만, 우리 페이지에 노출하려면 docs.json의 파싱과 css 흉내내기도 필연적이긴 합니다.

**Comment by uriyang** [comment]
러시아 리포 참고해서 새 브랜치 구성하는 걸로 변경되었습니다.
