### ISSUE TITLE
번역 프로세스 정의

### ISSUE THREAD

**Issue by SeongJuMoon** [beewee22/svelte.kr#9]
해당 이슈에 쓰레드에서 이야기를 나눠보죠.

**Comment by beewee22** [comment]
일단.. 고민해볼 문제들

1. 어디에 어떻게 저장해둘 것인가? (영문 원본을 두고 .kr 확장자를 붙인 새 파일에 저장하게 할 것인가? 아니면 브랜치를 새로 딸 것인가?? 등등)
2. 어떻게 하면 중복 작업을 피할 수 있을까?? 
3. 검수는 어떻게 할 것인가???

**Comment by uriyang** [comment]
2.는 범위를 나누면 되지 않을까요?

**Comment by SeongJuMoon** [comment]
>1. 어디에 어떻게 저장해둘 것인가? (영문 원본을 두고 .kr 확장자를 붙인 새 파일에 저장하게 할 것인가? 아니면 브랜치를 새로 딸 것인가?? 등등)

전체적인 번역 브랜치를 판 후 해당 md나 이런 파일을 번역하는 브랜치를 별도로 파서 작업하는게 어떨까요?
> 2.어떻게 하면 중복 작업을 피할 수 있을까??

작업이전에 해당 카테고리를 직접 assign 하고 작업하여 중복 작업을 방지하는게 어떨까 합니다.

> 3. 검수는 어떻게 할 것인가???

작업이 완료된 브랜치에 한해 번역브랜치로 `pull request`를 날리고 4인이상의 리뷰어에게 승인을 받도록 하는게 어떨까요?

더 좋은 의견이 있다면 남겨주세요.

**Comment by beewee22** [comment]
> > 1. 어디에 어떻게 저장해둘 것인가? (영문 원본을 두고 .kr 확장자를 붙인 새 파일에 저장하게 할 것인가? 아니면 브랜치를 새로 딸 것인가?? 등등)
> 
> 전체적인 번역 브랜치를 판 후 해당 md나 이런 파일을 번역하는 브랜치를 별도로 파서 작업하는게 어떨까요?
> 
> > 2.어떻게 하면 중복 작업을 피할 수 있을까??
> 
> 작업이전에 해당 카테고리를 직접 assign 하고 작업하여 중복 작업을 방지하는게 어떨까 합니다.
> 
> > 1. 검수는 어떻게 할 것인가???
> 
> 작업이 완료된 브랜치에 한해 번역브랜치로 `pull request`를 날리고 4인이상의 리뷰어에게 승인을 받도록 하는게 어떨까요?
> 
> 더 좋은 의견이 있다면 남겨주세요.


제일 현실적인 답안 같아요. 일단 번역 브랜치를 메인으로, 각 챕터별로 assignee들이 따로 브랜치를 파든 해서 pr로 병합하면 될 것 같아요
그리고 저희 3+a 해서 메인 검수자들을 모집해두는게 좋겠네요. 번역을 하실 분들과 검수자로 해서 기여를 받으면 될 듯. 검수자는 최대 8명 정도가 나을 것 같구요.(최소 4인 이상이 컨펌을 하면 통과인걸로)

**Comment by sukyology** [comment]
성주님 의견에 찬성하고, 
번역한 문서 파일 네이밍 룰 정도만 정하면 좋을 것 같습니다. 

기존 영문 문서를 남겨두고 작업한다는 가정하에... 
{원본파일명}-kr.md 라던가...

**Comment by uriyang** [comment]
그럼 우선 번역 브랜치부터 해결하죠~

feature/translation 브랜치까 있는데, 이 브랜치 사용하면 될까요?
아님 다른 용도로 만드신건가요?

**Comment by beewee22** [comment]
아마 그 브랜치가 번역 메인 브랜치가 되게 하려고 만드신 것 같아요. 근데 생각해보니 새로 유입되는 번역 인력이 헷갈려 할 것도 같아서.. 반대로 translation 브랜치를 영문 원본 보존용으로 두고 마스터 쪽에서 머지 받으면 어떨까요???

정리하면,
1. 번역은 매 챕터 단위로 나눠서 챕터별로 번역 인원들을 assign 후에 각 번역 인원은 master브랜치로 PR.
2. 번역 검수는 4~8인의 검수자를 두고 4인 이상의 검수를 얻어야 머지하도록

**Comment by sukyology** [comment]
마스터에 머지하는 거 좋은 것 같습니다.
 튜토리얼 번역하는 거죠? 
단위도 적당한 것 같아요.

**Comment by uriyang** [comment]
러시아 리포 참고해서 새 브랜치 구성하는 걸로 변경되었습니다.
